export const endpoints = {
  health: '/api/health',
  resultOverview: '/api/result-overview',
  scoringSummary: '/api/scoring-summary',
  recommendedActions: '/api/recommended-actions',
  auth: {
    login: '/api/auth/login',
    verify: '/api/auth/verify',
    configStatus: '/api/config/status',
  },
  dashboard: {
    summary: '/api/dashboard/summary',
  },
  audit: {
    summary: '/api/account-audit/summary',
    intake: '/api/account-audit/intake',
    intakeUpload: '/api/account-audit/intake-upload',
    intakeJobs: '/api/account-audit/intake-jobs',
    mt5TestConnection: '/api/account-audit/mt5/test-connection',
    mt5Connect: '/api/account-audit/mt5/connect',
    mt5Connections: '/api/account-audit/mt5/connections',
    mt5Connection: (connectionId: number) => `/api/account-audit/mt5/${connectionId}`,
    mt5Sync: (connectionId: number) => `/api/account-audit/mt5/${connectionId}/sync`,
    summariesRecompute: '/api/account-audit/summaries/recompute',
    summaries: '/api/account-audit/summaries',
    summary: (summaryId: number) => `/api/account-audit/summaries/${summaryId}`,
    review: '/api/account-audit/review',
    timeline: '/api/account-audit/timeline',
  },
  backtests: {
    list: '/api/backtests/list',
    candidate: (strategyId: string) => `/api/backtests/${strategyId}/candidate`,
    lifecycle: (strategyId: string) => `/api/backtests/${strategyId}/lifecycle`,
    timeline: (strategyId: string) => `/api/backtests/${strategyId}/timeline`,
    import: '/api/backtests/import',
    importUpload: '/api/backtests/import-upload',
  },
  forwardGate: {
    summary: '/api/forward-gate/summary',
  },
  forwardRuns: {
    list: '/api/forward-runs',
    updateStatus: (runId: number) => `/api/forward-runs/${runId}/status`,
    gateResult: (runId: number) => `/api/forward-runs/${runId}/gate-result`,
  },
  gateResults: {
    list: '/api/gate-results',
  },
  evaluations: {
    history: '/api/evaluations/history',
  },
  importJobs: {
    list: '/api/import-jobs',
    changes: (jobId: number) => `/api/import-jobs/${jobId}/changes`,
    activate: (jobId: number) => `/api/import-jobs/${jobId}/activate`,
    compare: '/api/import-jobs/compare',
  },
  auditCases: {
    list: '/api/audit-cases',
    create: '/api/audit-cases',
    detail: (caseId: number) => `/api/audit-cases/${caseId}`,
    update: (caseId: number) => `/api/audit-cases/${caseId}`,
    reviewQueue: '/api/review-queue',
    summary: '/api/audit-cases/stats/summary',
    notes: (caseId: number) => `/api/audit-cases/${caseId}/notes`,
    actions: (caseId: number) => `/api/audit-cases/${caseId}/actions`,
    decision: (caseId: number) => `/api/audit-cases/${caseId}/decision`,
    timeline: (caseId: number) => `/api/audit-cases/${caseId}/timeline`,
  },
  backtestsActiveDataset: '/api/backtests/active-dataset',
} as const
